[package]
name = "snake-game"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { version = "0.4.22", features = ["max_level_trace", "release_max_level_error"] }
pretty_env_logger = "0.5.0"
flynes = {path = "../../.", version = "0.1.0"}
rand = "0.9.2"
sdl2 = "0.38.0"
